version: '3.7'

services:
  api:
    container_name: api-messaging-micro
    image: node:10.16.0
    volumes:
      - $PWD:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      RABBITMQ_CONNECTION_URL: amqp://rabbit:5672
      MYSQL_CONNECTION_URL: mysql://root:secret@mysql:3306/micro_services
    command: yarn nodemon messaging/api.js
    networks:
      - net

  worker:
    container_name: worker-messaging-micro
    image: node:10.16.0
    volumes:
      - $PWD:/app
    working_dir: /app
    environment:
      RABBITMQ_CONNECTION_URL: amqp://rabbit:5672
      MYSQL_CONNECTION_URL: mysql://root:secret@mysql:3306/micro_services
    command: yarn nodemon messaging/worker.js
    networks:
      - net

networks:
  net:
    driver: bridge
